### ISSUE TITLE
Summary: Meets Expectations

### ISSUE THREAD

**Issue by melissamcewen** [stevedu15/prj-rev-bwfs-dasmoto#1]
Hi I'm reviewing for codecademy. Great job on this! Your HTML is structured really well. Your CSS is off to a great start and I'll open up some "issues" to get your to 100%.

I hope you enjoyed making this, you're definitely ready for the next part of the course!

**Comment by stevedu15** [comment]
Hi Melissa @melissamcewen, thank you so much for the review. It makes a lot of sense. and i will keep working on my skills to keep the code as simple as possible. Hopefully, I can get your review again next time and you can see if I am getting better. Thank you!
